version: "3.9"

services:

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      PGUSER: admin
      PGPASSWORD: admin
    ports:
    - 5432:5432
    healthcheck:
     test: ["CMD-SHELL", "pg_isready -U admin"]
     interval: 10s
     timeout: 5s
     retries: 5
